### ISSUE TITLE
os.getenv('username') doesnt exist on linux

### ISSUE THREAD

**Issue by alexanderrichtertd** [alexanderrichtertd/plex#51]
Traceback (most recent call last):
  File "pipeline.py", line 180, in <module>
    Setup()
  File "pipeline.py", line 51, in __init__
    self.set_pipeline_env()
  File "pipeline.py", line 100, in set_pipeline_env
    os.environ['DATA_USER_PATH']      = self.data_pipeline_path[0] + '/data/user/' + os.getenv('username')
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by alexanderrichtertd** [comment]
import os
import pwd

def get_username():
    return pwd.getpwuid( os.getuid() )[ 0 ]

pwd.getpwuid(os.getuid()).pw_name

https://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python

**Comment by alexanderrichtertd** [comment]
getpass.user()
