### ISSUE TITLE
Plex doesn't load in 2024

### ISSUE THREAD

**Issue by alexanderrichtertd** [alexanderrichtertd/plex#54]
Start leads to nothing - no start - while paths are incorrect due to space issues:

```
'G:\My' is not recognized as an internal or external command,
operable program or batch file.

G:\My Drive\3 RESOURCES\github\plex\exe\windows>python \pipeline.py  --software desktop
python: can't open file 'G:\\pipeline.py': [Errno 2] No such file or directory
G:\My Drive\3 RESOURCES\github\plex\exe\windows>
```

**Comment by alexanderrichtertd** [comment]
Fix1: Add quotes to batch paths to avoid space issues on Windows:
`CALL "%~dp0\setup_env.bat"`

**Comment by alexanderrichtertd** [comment]
Yaml error error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\My Drive\3 RESOURCES\github\plex\data\pipeline.py", line 20, in <module>
    import yaml
  File "G:\My Drive\3 RESOURCES\github\plex\lib\extern\yaml\__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
C:\Users\alexa>
```

**Comment by alexanderrichtertd** [comment]
Update external libraries:
- Qt.py to add PySide 6
- Yaml to include Python 3 updates

**Comment by alexanderrichtertd** [comment]
- Yaml loader issues: [Update of load to include 'Loader=yaml.Loader' as an argument.](https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col)
- SmartDict: [Removal of has_key to just 'in' for dict](https://stackoverflow.com/questions/33727149/dict-object-has-no-attribute-has-key)

**Comment by alexanderrichtertd** [comment]
Python 3 exception: [Can't use , anymore to separate  exception type and variable](https://stackoverflow.com/questions/70648404/syntaxerror-multiple-exception-types-must-be-parenthesized)
`SyntaxError: multiple exception types must be parenthesized`

Instead: except OSError(e):

**Comment by alexanderrichtertd** [comment]
Python 3 reload: Needs import [importlib.reload](https://docs.python.org/3/library/importlib.html#importlib.reload)
[NameError: name 'reload' is not defined. Did you mean: 'arLoad'?](url)

**Comment by alexanderrichtertd** [comment]
Pyside issue: Install PySide 6 and removed 2nd integer.

```
TypeError: 'PySide2.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide2.QtWidgets.QBoxLayout.addWidget(QWidget, int, int)
Supported signatures:
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget, int = 0, PySide2.QtCore.Qt.Alignment = Default(Qt.Alignment))
  PySide2.QtWidgets.QBoxLayout.addWidget(PySide2.QtWidgets.QWidget)
```
